#!/bin/zsh
alias \
    ls="ls -tru" \
    v="nvim" \
    vim="nvim" \
    szrc="source ~/.zshrc" \
    svrc="source ~/.config/nvim/init.vim" \
    gh="cd ~/" \
    gb="cd ~/bin" \
    gc="cd ~/.config" \
    evrc="vim ~/.config/nvim/init.vim" \
    earc="vim ~/.config/aliasrc" \
    ezrc="vim ~/.config/zsh/zshrc" \
    eyrc="vim ~/.config/yabai/yabairc" \
    esrc="vim ~/.config/skhd/skhdrc" \
