#!/bin/zsh
alias \
    ls="lsd -tr" \
    v="nvim" \
    vim="nvim" \
    szrc="source ~/.zshrc" \
    svrc="source ~/.config/nvim/init.vim" \
    yy="echo -e '!!' | pbcopy" \
    yphrase="head -n 1 ~/.ssh/vulcan | tr -d '\n' | pbcopy" \
    gc="cd ~/.config" \
    evrc="nvim ~/.config/nvim/init.vim" \
    earc="nvim ~/.config/aliasrc" \
    ezrc="nvim ~/.config/zsh/zshrc" \
    eyrc="nvim ~/.config/yabai/yabairc" \
    esrc="nvim ~/.config/skhd/skhdrc" \
    vv="nvim -c VimwikiIndex"\ 
    ebmks="nvim ~/.config/bookmarks" \
    ezext="nvim ~/.config/zextensions" \
    ekrc="nvim ~/.config/kitty/kitty.conf" \
    vurls="bat ~/Documents/almanac/urls.md" \
    eurls="nvim ~/Documents/almanac/urls.md" \
    copyLastCmd="fc -ln -1 | awk '{\$1=\$1}1' | tr -d "\n" | pbcopy " \
    gs="git status" \
    tm="~/bin/tm" \
#vv="cd ~/Documents/almanac && nvim ~/Documents/almanac/index.md" \
#gh="cd ~/" \
#gb="cd ~/bin" \
