#!/bin/zsh
go() {
bookmarks=/Users/tyyiu/.config/bookmarks
choice=$(cat $bookmarks | cut -d ":" -f1 | fzf +m) && \
cd $(grep $choice $bookmarks | cut -d ":" -f2)
}

export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"

export FZF_TMUX=1
setopt HIST_IGNORE_ALL_DUPS
export HISTTIMEFORMAT="[%F %T] "
setopt EXTENDED_HISTORY
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
#setopt INC_APPEND_HISTORY
